name: Send Test Email Init
on: [workflow_dispatch]  						# 手动触发工作流
jobs:
  send-email:
    runs-on: ubuntu-latest
    steps:
    - name: Send Test Email
      uses: docker://pascalgn/send-email-action:v0.15.0
      with:
        from: ${{ secrets.SMTP_USER }}
        to: lsj@mail.zjgsu.edu..cn  						# 接收测试邮件的邮箱地址
        subject: Test Email from GitHub Actions
        body: This is a test email sent from GitHub Actions(wx-test1).
        host: ${{ secrets.SMTP_HOST }}
        port: ${{ secrets.SMTP_PORT }}
        user: ${{ secrets.SMTP_USER }}
        password: ${{ secrets.SMTP_PASSWORD }}
        tls: true
